package qmul.ds.interactiveInduction;


import edu.stanford.nlp.util.Pair;
import org.apache.log4j.Logger;

import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class EvalResult {
        private static final Logger logger = Logger.getLogger(EvalResult.class);

    private final HashMap<Integer, HashMap<String, HashMap<String, Double>>> semanticAccuracy;  // Description: top-n -> dataset -> metric -> value
    private final HashMap<Integer, HashMap<String, ArrayList<Double>>> parsingCoverage;  // Description: top-n -> dataset -> (coverage, exact match)
    private final HashMap<Pair<String, Integer> , List<String>> failedParses; // Description: (dataset, top-n) -> failed parses
    private final HashMap<Pair<String, Integer> , List<String>> failedExactMatches; // Description: (dataset, top-n) -> failed exact matches
    private final List<String> datasetNames;
    private final List<Integer> datasetSizes;
//    private final String metadata;  // TODO use.
    // ----------------------------- Constructors -----------------------------
    public EvalResult(HashMap<Integer, HashMap<String, HashMap<String, Double>>> semanticAccuracy,
                                HashMap<Integer, HashMap<String, ArrayList<Double>>> parsingCoverage) {
        this.semanticAccuracy = semanticAccuracy;
        this.parsingCoverage = parsingCoverage;
        this.failedParses = new HashMap<>();
        this.failedExactMatches = new HashMap<>();
        this.datasetNames = new ArrayList<>();
        this.datasetSizes = new ArrayList<>();
//        this.metadata = "";
    }


    public EvalResult() {
        this.semanticAccuracy = new HashMap<>();
        this.parsingCoverage = new HashMap<>();
        this.failedParses = new HashMap<>();
        this.failedExactMatches = new HashMap<>();
        this.datasetNames = new ArrayList<>();
        this.datasetSizes = new ArrayList<>();
//        this.metadata = "";
    }


    public HashMap<Integer, HashMap<String, HashMap<String, Double>>> getSemanticAccuracy() {
        return semanticAccuracy;
    }

    public HashMap<Integer, HashMap<String, ArrayList<Double>>> getParsingCoverage() {
        return parsingCoverage;
    }


    public double getTrainAccuracy(int n, String metric) {
        return this.semanticAccuracy.get(n).get("train").get(metric);
    }


    public double getTestAccuracy(int n, String metric) {
        return this.semanticAccuracy.get(n).get("test").get(metric);
    }


    /**
     * Updates or adds semantic accuracy results for a specific top-N configuration.
     */
    public void addSemanticAccuracy(int topN, String dataset, double precision, double recall, double f1) {
        HashMap<String, HashMap<String, Double>> datasetMap = semanticAccuracy.getOrDefault(topN, new HashMap<>());
        HashMap<String, Double> scores = new HashMap<>();
        scores.put("precision", precision);
        scores.put("recall", recall);
        scores.put("f1", f1);
        datasetMap.put(dataset, scores);
        semanticAccuracy.put(topN, datasetMap);
    }


    /**
     * Updates or adds parsing coverage results for a specific top-N configuration.
     */
    public void addParsingCoverage(int topN, String dataset, double coverage, double exactMatch) {
        HashMap<String, ArrayList<Double>> coverageMap = parsingCoverage.getOrDefault(topN, new HashMap<>());
        coverageMap.put(dataset, new ArrayList<>(Arrays.asList(coverage, exactMatch)));
        parsingCoverage.put(topN, coverageMap);
    }


    /**
     * Adds a single failed parse result for diagnostics.
     */
    public void addFailedParse(String dataset, int topN, String sentence) {
        Pair<String, Integer> key = new Pair<>(dataset, topN);
        failedParses.computeIfAbsent(key, k -> new ArrayList<>()).add(sentence);
    }


    /**
     * Adds a single failed exact match result for diagnostics.
     */
    public void addFailedExactMatch(String dataset, int topN, String sentence) {
        Pair<String, Integer> key = new Pair<>(dataset, topN);
        failedExactMatches.computeIfAbsent(key, k -> new ArrayList<>()).add(sentence);
    }


    public void setDatasetNames(String trainName, String testName) {
        this.datasetNames.add(trainName);
        this.datasetNames.add(testName);
    }

    public void setDatasetSizes(int trainSize, int testSize) {
        this.datasetSizes.add(trainSize);
        this.datasetSizes.add(testSize);
    }



    /**
     * Returns the semantic accuracy results generated by evaluate_model as a table.
     */
    public String getSemanticAccResultsTable(String info) {  //todo add a variable called metadata, update it whenever, and then print that, instead of using  a param to this method.
        String semAccResults = "";
        String leftAlignFormat = "| %-15s | %6.2f | %6.2f | %6.2f | %6.2f | %6.2f | %6.2f |%n";
        String rowSeparator = "+-----------------+--------+--------+--------+--------+--------+--------+";
        if (!datasetNames.isEmpty())
            info += " | training set name: " + datasetNames.getFirst() + " | testing set name: " + datasetNames.getLast();
        if (!datasetSizes.isEmpty())
            info += " | train size: " + datasetSizes.getFirst() + " | test size: " + datasetSizes.getLast();
//        if (!info.isEmpty())
        semAccResults += "\n" + info + "\n";
        semAccResults += "\n====================| Semantic Accuracy Results |====================\n";
        semAccResults += "\n+-----------------+--------------------------+--------------------------+";
        semAccResults += String.format("\n| Actions \\ Data  |           Train          |          Test            |%n");
        semAccResults += "|                 +--------------------------+--------------------------+";
        semAccResults += String.format("\n|                 |   P    |    R   |   F1   |   P    |    R   |   F1   |%n");
        semAccResults += rowSeparator + "\n";

        for (int topN : semanticAccuracy.keySet()) {
            HashMap<String, Double> trainScores = semanticAccuracy.get(topN).get("train");
            HashMap<String, Double> testScores = semanticAccuracy.get(topN).get("test");
            String s = String.format(leftAlignFormat, "Top-" + topN, trainScores.get("precision"), trainScores.get("recall"),
                    trainScores.get("f1"), testScores.get("precision"), testScores.get("recall"), testScores.get("f1"));
            semAccResults += s;
        }
        semAccResults += rowSeparator;
        return semAccResults;
    }


    /**
     * get the parsing coverage results generated by evaluate_model as a table.
     */
    public String getParsingCoverageResultsTable(String info) {
        String parsingCoverage_results = "";
        String leftAlignFormat = "| %-15s | %10.2f | %11.2f | %10.2f | %11.2f |%n";
        String rowSeparator = "+-----------------+------------+-------------+------------+-------------+";

        parsingCoverage_results += "\n====================| Parsing Coverage Results |====================\n";
        if (!info.isEmpty())
            parsingCoverage_results += info + "\n";
        parsingCoverage_results += "+-----------------+--------------------------+--------------------------+\n";
        parsingCoverage_results += String.format("| Actions \\ Data  |           Train          |          Test            |%n");
        parsingCoverage_results += "|                 +--------------------------+--------------------------+\n";
        parsingCoverage_results += String.format("|                 |  Coverage  | Exact Match |  Coverage  | Exact Match | %n");
        parsingCoverage_results += rowSeparator + "\n";

        for (int topN : parsingCoverage.keySet()) {
            HashMap<String, ArrayList<Double>> coverageScores = parsingCoverage.get(topN);
            ArrayList<Double> trainScores = coverageScores.get("train");
            ArrayList<Double> testScores = coverageScores.get("test");
            parsingCoverage_results += String.format(leftAlignFormat, "Top-" + topN, trainScores.get(0), trainScores.get(1), testScores.get(0), testScores.get(1));
        }
        parsingCoverage_results += rowSeparator;
        return parsingCoverage_results;
    }


    /**
     * Returns diagnostic information about failed parses and exact matches as a formatted string.
     */
    public String getDiagnosticResults() {
        StringBuilder diagnostics = new StringBuilder();
        diagnostics.append("\n =====================| Diagnostics |=====================\n\n");

        diagnostics.append("***** Failed Parses *****\n");
        if (failedParses.isEmpty()) {
            diagnostics.append("No failed parses.\n");
        } else {
            for (Pair<String, Integer> key : failedParses.keySet()) {
                diagnostics.append(String.format(">>> Dataset: %s | Top-%d | Failed Parses:%n",
                    key.first(), key.second()));
                for (String sentence : failedParses.get(key)) {
                    diagnostics.append(sentence).append("\n");
                }
            }
        }

        diagnostics.append("\n***** Failed Exact Matches *****\n");
        if (failedExactMatches.isEmpty()) {
            diagnostics.append("No failed exact matches.\n");
        } else {
            for (Pair<String, Integer> key : failedExactMatches.keySet()) {
                diagnostics.append(String.format(">>> Dataset: %s | Top-%d | Failed Exact Matches:%n",
                    key.first(), key.second()));
                for (String sentence : failedExactMatches.get(key)) {
                    diagnostics.append(sentence).append("\n");
                }
            }
        }

        return diagnostics.toString();
    }


    /**
     * Writes the evaluation results to a file.
     */
    public void writeResultsToFile(String resultsPath, String outputFileName) {
        FileWriter fw;
        // Report file:
        try {
            fw = new FileWriter(resultsPath +"eval_result_" + outputFileName + ".txt");
            fw.write(getSemanticAccResultsTable("sem acc"));  //todo fix
            fw.write("\n\n\n");
            fw.write(getParsingCoverageResultsTable("coverage"));
            fw.write("\n\n\n");
            fw.write(getDiagnosticResults());
            fw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        // TSV file:
        this.toTSVString(true, true, resultsPath);
    }


    /**
     * Overloads the method below, used for when we only want the string and no need for saving it.
     * @return the results as TSV string.
     */
    public String toTSVString() {
        return toTSVString(false, false, "");
    }


    public String toTSVString(boolean saveToFile, boolean addHeader, String savePath) {
        StringBuilder sb = new StringBuilder();
        String header = "TopN\tResultsOn\tTrainName\tTrainSize\tTestName\tTestSize\tPrecision\tRecall\tF1\tCoverage\tExactMatch\n";
        if(addHeader)
            sb.append(header);

        for (int topN : semanticAccuracy.keySet()) {
            for (String dataset : semanticAccuracy.get(topN).keySet()) {
                HashMap<String, Double> scores = semanticAccuracy.get(topN).get(dataset);
                    Double coverage = parsingCoverage.get(topN).get(dataset).getFirst();
                    Double em = parsingCoverage.get(topN).get(dataset).getLast();
                    String trainName = "None";
                    String testName = "None";
                    if (!datasetNames.isEmpty()) {
                        trainName = this.datasetNames.getFirst();
                        testName = this.datasetNames.getLast();
                    }
                    int trainSize = -1;
                    int testSize = -1;
                    if (!datasetSizes.isEmpty()) {
                        trainSize = this.datasetSizes.getFirst();
                        testSize = this.datasetSizes.getLast();
                    }
                    sb.append(topN).append("\t")
                            .append(dataset).append("\t")
                            .append(trainName).append("\t")
                            .append(trainSize).append("\t")
                            .append(testName).append("\t")
                            .append(testSize).append("\t")
                            .append(scores.get("precision")).append("\t")
                            .append(scores.get("recall")).append("\t")
                            .append(scores.get("f1")).append("\t")
                            .append(coverage).append("\t")
                            .append(em)
                            .append("\n");
            }
        }
        logger.trace("Results in TSV format:\n" + sb);

        // Save to file:
        if (saveToFile) {
            try {
                FileWriter fw = new FileWriter(savePath + "eval_result.tsv");
                fw.write(sb.toString());
                fw.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        return sb.toString();
    }

}