package qmul.ds.interactiveInduction;


import edu.stanford.nlp.util.Pair;

import java.io.FileWriter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class EvalResult {
    private final HashMap<Integer, HashMap<String, HashMap<String, Double>>> semanticAccuracy;
    private final HashMap<Integer, HashMap<String, ArrayList<Double>>> parsingCoverage;
    private final HashMap<Pair<String, Integer> , List<String>> failedParses;
    private final HashMap<Pair<String, Integer> , List<String>> failedExactMatches;

    // ----------------------------- Constructors -----------------------------
    public EvalResult(HashMap<Integer, HashMap<String, HashMap<String, Double>>> semanticAccuracy,
                                HashMap<Integer, HashMap<String, ArrayList<Double>>> parsingCoverage) {
        this.semanticAccuracy = semanticAccuracy;
        this.parsingCoverage = parsingCoverage;
        this.failedParses = new HashMap<>();
        this.failedExactMatches = new HashMap<>();
    }


    public EvalResult() {
        this.semanticAccuracy = new HashMap<>();
        this.parsingCoverage = new HashMap<>();
        this.failedParses = new HashMap<>();
        this.failedExactMatches = new HashMap<>();
    }


    /**
     * Updates or adds semantic accuracy results for a specific top-N configuration.
     */
    public void addSemanticAccuracy(int topN, String dataset, double precision, double recall, double f1) {
        HashMap<String, HashMap<String, Double>> datasetMap = semanticAccuracy.getOrDefault(topN, new HashMap<>());
        HashMap<String, Double> scores = new HashMap<>();
        scores.put("precision", precision);
        scores.put("recall", recall);
        scores.put("f1", f1);
        datasetMap.put(dataset, scores);
        semanticAccuracy.put(topN, datasetMap);
    }


    /**
     * Updates or adds parsing coverage results for a specific top-N configuration.
     */
    public void addParsingCoverage(int topN, String dataset, double coverage, double exactMatch) {
        HashMap<String, ArrayList<Double>> coverageMap = parsingCoverage.getOrDefault(topN, new HashMap<>());
        coverageMap.put(dataset, new ArrayList<>(Arrays.asList(coverage, exactMatch)));
        parsingCoverage.put(topN, coverageMap);
    }


    /**
     * Adds a single failed parse result for diagnostics.
     */
    public void addFailedParse(String dataset, int topN, String sentence) {
        Pair<String, Integer> key = new Pair<>(dataset, topN);
        failedParses.computeIfAbsent(key, k -> new ArrayList<>()).add(sentence);
    }


    /**
     * Adds a single failed exact match result for diagnostics.
     */
    public void addFailedExactMatch(String dataset, int topN, String sentence) {
        Pair<String, Integer> key = new Pair<>(dataset, topN);
        failedExactMatches.computeIfAbsent(key, k -> new ArrayList<>()).add(sentence);
    }



    /**
     * Returns the semantic accuracy results generated by evaluate_model as a table.
     */
    public String getSemanticAccResultsTable(String info) {
        String semAccResults = "";
        String leftAlignFormat = "| %-15s | %6.2f | %6.2f | %6.2f | %6.2f | %6.2f | %6.2f |%n";
        String rowSeparator = "+-----------------+--------+--------+--------+--------+--------+--------+";

        semAccResults += "\n====================| Semantic Accuracy Results |====================\n";
        if (!info.isEmpty())
            semAccResults += info + "\n";
        semAccResults += "\n+-----------------+--------------------------+--------------------------+";
        semAccResults += String.format("\n| Actions \\ Data  |           Train          |          Test            |%n");
        semAccResults += "\n|                 +--------------------------+--------------------------+";
        semAccResults += String.format("\n|                 |   P    |    R   |   F1   |   P    |    R   |   F1   |%n");
        semAccResults += rowSeparator + "\n";

        for (int topN : semanticAccuracy.keySet()) {
            HashMap<String, Double> trainScores = semanticAccuracy.get(topN).get("train");
            HashMap<String, Double> testScores = semanticAccuracy.get(topN).get("test");
            String s = String.format(leftAlignFormat, "Top-" + topN, trainScores.get("precision"), trainScores.get("recall"),
                    trainScores.get("f1"), testScores.get("precision"), testScores.get("recall"), testScores.get("f1"));
            semAccResults += s;
        }
        semAccResults += rowSeparator;
        return semAccResults;
    }


    /**
     * get the parsing coverage results generated by evaluate_model as a table.
     */
    public String getParsingCoverageResultsTable(String info) {
        String parsingCoverage_results = "";
        String leftAlignFormat = "| %-15s | %10.2f | %11.2f | %10.2f | %11.2f |%n";
        String rowSeparator = "+-----------------+------------+-------------+------------+-------------+";

        parsingCoverage_results += "====================| Parsing Coverage Results |====================\n";
        if (!info.isEmpty())
            parsingCoverage_results += info + "\n";
        parsingCoverage_results += "+-----------------+--------------------------+--------------------------+\n";
        parsingCoverage_results += String.format("| Actions \\ Data  |           Train          |          Test            |%n");
        parsingCoverage_results += "|                 +--------------------------+--------------------------+\n";
        parsingCoverage_results += String.format("|                 |  Coverage  | Exact Match |  Coverage  | Exact Match | %n");
        parsingCoverage_results += rowSeparator + "\n";

        for (int topN : parsingCoverage.keySet()) {
            HashMap<String, ArrayList<Double>> coverageScores = parsingCoverage.get(topN);
            ArrayList<Double> trainScores = coverageScores.get("train");
            ArrayList<Double> testScores = coverageScores.get("test");
            parsingCoverage_results += String.format(leftAlignFormat, "Top-" + topN, trainScores.get(0), trainScores.get(1), testScores.get(0), testScores.get(1));
        }
        parsingCoverage_results += rowSeparator;
        return parsingCoverage_results;
    }


    /**
     * Returns diagnostic information about failed parses and exact matches as a formatted string.
     */
    public String getDiagnosticResults() {
        StringBuilder diagnostics = new StringBuilder();
        diagnostics.append("\n =====================| Diagnostics |=====================\n\n");

        diagnostics.append("***** Failed Parses *****\n");
        if (failedParses.isEmpty()) {
            diagnostics.append("No failed parses.\n");
        } else {
            for (Pair<String, Integer> key : failedParses.keySet()) {
                diagnostics.append(String.format(">>> Dataset: %s | Top-%d | Failed Parses:%n",
                    key.first(), key.second()));
                for (String sentence : failedParses.get(key)) {
                    diagnostics.append(sentence).append("\n");
                }
            }
        }

        diagnostics.append("\n***** Failed Exact Matches *****\n");
        if (failedExactMatches.isEmpty()) {
            diagnostics.append("No failed exact matches.\n");
        } else {
            for (Pair<String, Integer> key : failedExactMatches.keySet()) {
                diagnostics.append(String.format(">>> Dataset: %s | Top-%d | Failed Exact Matches:%n",
                    key.first(), key.second()));
                for (String sentence : failedExactMatches.get(key)) {
                    diagnostics.append(sentence).append("\n");
                }
            }
        }

        return diagnostics.toString();
    }


    /**
     * Writes the evaluation results to a file.
     */
    public void writeResutlsToFile(String resultsPath) {
        FileWriter fw;
        try {
            fw = new FileWriter(resultsPath + "eval_results.txt");
            fw.write(getSemanticAccResultsTable("sem acc"));
            fw.write("\n\n\n");
            fw.write(getParsingCoverageResultsTable("coverage"));
            fw.write("\n\n\n");
            fw.write(getDiagnosticResults());
            fw.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}