package qmul.ds.learn;

import java.io.File;
import java.io.IOException;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import edu.stanford.nlp.ling.HasWord;
import org.apache.jena.tdb.store.Hash;
import org.apache.log4j.Logger;

import qmul.ds.formula.TTRRecordType;
import edu.stanford.nlp.ling.Sentence;
import edu.stanford.nlp.ling.Word;
import edu.stanford.nlp.util.Pair;

/**
 * Objects of this front-end class learn unknown words from a corpus of parsed sentences. The class provides methods for
 * parsing and loading corpora.
 * It makes use of a {@link Hypothesiser} to hypothesise whole action sequences that lead from the axiom tree to the
 * target tree. These are then split via {@code CandidateSequence.split()} into their comprising parts. These
 * different split possibilities are then handed over to the {@link WordHypothesisBase} for generalisation and
 * probability estimation/update. This happens incrementally, i.e. one training example at a time as they are
 * encountered in the corpus.
 * 
 * @author arash
 * 
 */

public class TTRWordLearner extends WordLearner<TTRRecordType>{
	
	public static final Logger logger=Logger.getLogger(TTRWordLearner.class);
	public static final String ANSI_RESET = "\u001B[0m";
	public static final String ANSI_GREEN = "\u001B[32m";
	public static final String ANSI_YELLOW = "\u001B[33m";
	public static final String ANSI_BLUE = "\u001B[34m";
	public static final String ANSI_PURPLE = "\u001B[35m";
	public static final String ANSI_CYAN = "\u001B[36m";
	public static final String ANSI_RED = "\u001B[31m";


	public TTRWordLearner(String seedResourceDir, RecordTypeCorpus c) {
		hypothesiser = new TTRHypothesiser(seedResourceDir);
		corpus = c;
		this.corpusIterator = corpus.iterator();
	}
	
	public TTRWordLearner(String resourceDir, String corpusFileName) {
		this(resourceDir);
		try {
			this.loadCorpus(new File(corpusFileName));
		} catch (IOException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
	}


	public TTRWordLearner(String seedResourceDir, RecordTypeCorpus trainingCorpus, WordHypothesisBase whb) {
		this.seedResourceDir = seedResourceDir;
		hypothesiser = new TTRHypothesiser(seedResourceDir);
		this.corpus = trainingCorpus;
		this.corpusIterator = corpus.iterator();
		if (whb != null) {
			this.hb = whb;
		} else {
			this.hb = new WordHypothesisBase();
		}
	}


	public TTRWordLearner(String seedResourceDir) {
		this.seedResourceDir= seedResourceDir; //"resource" + File.separator + "2013-english-ttr-induction-seed";
		hypothesiser = new TTRHypothesiser(seedResourceDir);
		corpus = null;

	}

	/**
	 * Generated by Copilot:
	 * Default constructor for the TTRWordLearner class.
	 * Initializes the seedResourceDir with a predefined path to the seed resource directory.
	 * Creates a new TTRHypothesiser with the seed resource directory.
	 * `seed` here refers to a beginning point for the lexicon and grammar (to not start from zero!): Ash
	 */
	public TTRWordLearner() {
		seedResourceDir="resource" + File.separator + "2013-english-ttr-induction-seed";
		hypothesiser = new TTRHypothesiser(seedResourceDir);
		corpus = null;
	}


	@Override
	public boolean learnOnce() {
		if (corpusIterator == null) {
			logger.info("No corpus loaded.");
			return false;
		}
		if (!corpusIterator.hasNext()) {
			logger.info("No more examples in the corpus.");
			return false;
		}

		Pair<Sentence<Word>, TTRRecordType> entry = corpusIterator.next();
		logger.info("Hypothesising sequences for utterance: " + entry.first());
		// logger.info("Hypothesising from training example: "+
		// sentence+"->"+target);
		long time = System.currentTimeMillis();
		Collection<CandidateSequence> hyps = null;
		try {
			((TTRHypothesiser)hypothesiser).loadTrainingExample(entry.first(), entry.second());
			hyps = hypothesiser.hypothesise();
			logger.info("\n");
			if (hyps.isEmpty()) {
				logger.warn(ANSI_YELLOW + "NO SEQUENCES RECEIVED from hypothesiser! skipping... " + ANSI_RESET);
//				System.out.println("no sequences returned, skipping this");
				skipped.add(entry);
				return true;
			}
		} catch (Exception e) {
			logger.error("problem hypothesising. Sentence:" + entry);
			e.printStackTrace();
			logger.error("Skipping...");
			skipped.add(entry);
			return true;
		}
		logger.info(ANSI_GREEN +  "Got " + hyps.size() + " sequences from Hypothesiser for "+ entry.second() + ANSI_RESET);
		logger.info(ANSI_GREEN);
		for(CandidateSequence cs: hyps)
		{
			logger.info(cs.toShortString());

		}
		logger.info(ANSI_RESET);

		logger.info(ANSI_GREEN + "Now splitting the sequences..." + ANSI_RESET);
		// DAGHypothesiser.printHypMap(hyps);
		Collection<Word> unknownWords = getUnknownWords(entry.first());

		hb.forgetCurrentDist();
		int totalSplit = 0;  // AA: Better be called `totalSplits`!
		int i = 0;
		try {

			for (CandidateSequence cs: hyps) {  // TODO Potential parallelisable loop
				i++;
				logger.debug("Splitting: " + cs.toShortString());
				Set<List<CandidateSequence>> splitSequences = cs.split();
				for (List<CandidateSequence> seq: splitSequences) {
					logger.trace("Result: " + seq + "\n");
				}

				totalSplit += splitSequences.size();
				logger.debug(i + ":" + splitSequences.size()+ " ");
				logger.debug("Adding split sequences to hypothesis base...");

				hb.addSequenceTuples(splitSequences);
			}

			logger.info("\n");
			this.hb.updateDistsEndOfExample(unknownWords);
			logger.info("Processing took:"+ (System.currentTimeMillis()-time)/1000 + " seconds");  // AA Not working correctly!
		} catch (Exception e) {
			logger.fatal("problem while updating distributions on sentence:" + entry);
			logger.fatal("this is fatal :(");
			e.printStackTrace();
			System.exit(1);
		}

		return true;
	}

	private Collection<Word> getUnknownWords(Sentence<Word> sent) {
		HashSet<Word> result = new HashSet<Word>();
		for (Word w: sent)
		{
			if (!this.hypothesiser.seedLexicon.containsKey(w.word()))
				result.add(w);
		}
		return result;
	}


	@Override
	public void loadCorpus(File corpusFile) throws IOException, ClassNotFoundException {
		RecordTypeCorpus c=new RecordTypeCorpus();
		c.loadCorpus(corpusFile);
		this.corpus=c;
		this.corpusIterator=this.corpus.iterator();
	}


	public void setTrainingCorpus(RecordTypeCorpus corpus) {
//		RecordTypeCorpus c=new RecordTypeCorpus();
//		c.loadCorpus(corpusFile);
		this.corpus=corpus;
		this.corpusIterator=this.corpus.iterator();
	}

	
	public static void main(String[] args) {
		String babyDSPath = "resource\\2025-babyds-seeded-induction\\".replace("\\", File.separator);  // fix later
		String corpusPath = babyDSPath + "class1-debug.txt";

		TTRWordLearner learner = new TTRWordLearner(babyDSPath, corpusPath);

		learner.learn();
		//System.out.println(learner.hypothesiser.targetIndependentHyps);
	}


}
